export const tags = [
    "simulación",
    "aventura",
    "granja",
    "relajante",
    "animales",
    "pueblo",
    "Stardew Valley",
    "supervivencia",
    "mar",
    "exploración",
    "Subnautica",
    "acción",
    "mundo abierto",
    "armas",
    "GTA V",
    "RPG",
    "fantasía",
    "Skyrim",
    "horror",
    "psicológico",
    "survival",
    "suspenso",
    "Silent Hill 2",
    "zombies",
    "multijugador",
    "DayZ",
    "terror",
    "caníbales",
    "bosque",
    "The Forest",
    "survival horror",
    "Resident Evil 4 Remake",
    "post-apocalíptico",
    "Death Stranding",
    "construcción",
    "Grounded",
    "sigilo",
    "puzzle",
    "IA",
    "vecinos",
    "Hello Neighbor 2",
    "ARPG",
    "Black Myth: Wukong",
    "estrategia",
    "Project Zomboid",
    "rogue-like",
    "The Binding of Isaac",
    "indie",
    "Stray",
    "sandbox",
    "creativo",
    "Minecraft",
    "metroidvania",
    "plataformas",
    "Ori and the Blind Forest",
    "Ori and the Will of the Wisps",
    "thriller",
    "suspenso",
    "Twelve Minutes",
    "narrativa",
    "fantasmas",
    "Shady Part of Me",
    "The Walking Dead: Season 1",
    "The Walking Dead: Season 2",
    "The Walking Dead: Season 3",
    "The Walking Dead: Season 4",
    "The Walking Dead: Michonne",
    "lucha",
    "Mortal Kombat",
    "vida",
    "Los Sims 4",
    "Herdling",
    "The Last of Us Part I",
    "The Last of Us Part II",
    "Ori and the Blind Forest",
    "Assassin’s Creed",
    "Assassin’s Creed Valhalla",
    "Assassin’s Creed Mirage",
    "Assassin’s Creed Shadows",
    "Senua’s Saga: Hellblade II",
    "Hellblade: Senua’s Sacrifice",
    "Hollow Knight",
    "60 Seconds!"

]